apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
    name: ingress-srv
    annotations: # Help ingress-controller understand that we are trying to feed routing rules.
        kubernetes.io/ingress.class: nginx
        nginx.ingress.kubernetes.io/use-regex: 'true' # For using regular expression (used in "path")
spec:
    rules:
        - host: posts.com
          http:
            paths:
                - path: /posts/create
                  backend:
                    serviceName: posts-clusterip-srv
                    servicePort: 4000
                - path: /posts
                  backend:
                    serviceName: query-srv
                    servicePort: 4002
                - path: /posts/?(.*)/comments
                  backend:
                    serviceName: comments-srv
                    servicePort: 4001
                - path: /?(.*) # If using wildcard route, it has to be placed at the bottom of config, as the config is read from top to the bottom
                  backend:
                    serviceName: client-srv
                    servicePort: 3000
